### PR TITLE
Validate signature against root

### LINKED ISSUE #4: setup CI to run unit tests

### LINKED ISSUE #30: validate that Coo seed matches the root/layer files
in addition to #1 , this helps users avoid misconfiguration, and debug issues faster.
* this might break usages of Coo to deliberately use a wrong seed - used in IRI regression to generate an invalid milestone. - this can be treated by an additional flag.

### LINKED ISSUE #39: Use latest `iota-java` release instead of custom built jota jarfile
Current JOTA jar is modified to support reference parameter for gTTA. Latest beta release has that fix in as well.

### PR DESCRIPTION
**Pull request by th0br0**
This PR adds an additional step to milestone generate which validates the signature retrieved from the SignatureSource against the root & siblings, thereby validating that the layers match the SignatureSource's seed.

Fixes #4 
Fixes #30 
Fixes #39

### CODE REVIEW

File: compass/Coordinator.java [hunk 1]
```diff
@@ -63,6 +67,14 @@ public Coordinator(CoordinatorConfiguration config, SignatureSource signatureSou
         .host(this.node.getHost())
         .port(Integer.toString(this.node.getPort()))
         .build();
+
+    validatorAPIs = config.validators.stream().map(url -> {
```
Comment (karimodm) [inline compass/Coordinator.java]: If no validators are passed, this will result in a NullPointerException.

File: compass/Coordinator.java [hunk 2]
```diff
@@ -202,6 +214,30 @@ private void start() throws ArgumentException, InterruptedException {
...
+              response = api.checkConsistency(trunk, branch);
+              if(!response.getState()) {
+                log.error("{} reported invalid consistency: {}", api.getHost(), response.getInfo());
+              }
+              return response.getState();
+            } catch (ArgumentException e) {
+              e.printStackTrace();
+              return false;
+            }
+          }).reduce(true, (a, b) -> a && b);
```
Comment (alon-e) [inline compass/Coordinator.java]: I think `allMatch(true)` is more readable than `reduce` (& will be more efficient in the sense that enough that 1 violates it will stop).

File: compass/conf/CoordinatorConfiguration.java [hunk 3]
```diff
@@ -49,4 +51,7 @@
   @Parameter(names = "-index", description = "Starting milestone index (inclusive)")
   public Integer index;
 
+  @Parameter(names = "-validator", description = "Validator nodes to use")
```
[the remark this answers is not in the document]
Comment (th0br0) [reply compass/conf/CoordinatorConfiguration.java]: We support passing this flag multiple times (hence why this is an array)
i.e.
`-validator http://localhost... -validator google.com -validator ...`

http://jcommander.org/#_lists
