### PR TITLE
Shutdown hook for a graceful exit

### LINKED ISSUE #98: If compass restarts before the state is stored we may have an inconsistent state
### Bug description
Scenario:
1. Milestone with index `n` is broadcasted.
2. Compass shuts down without storing state
3. Compass is restarted and then there could be 2 scenarios:
   a. IRI didn't track the latest milestone, thus the state seems consistent, and milestone `n` is recreated
   b. IRI did track the latest milestone and compass sees that the internal state doesn't match IRI's state. It will try to repropagate milestone `n-1` a few times and then give out a `RuntimeExcepion`

3a is the more dangerous scenario but it is unlikely to happen
3b is more likely but it will not do serious harm and it can be fixed by passing `--index` manually.

### PR DESCRIPTION
**Pull request by karimodm**
Shutdown happens only when bootstrap is over and node is fully synced against the latest milestone.

Fixes #98

### CODE REVIEW

**Comment by alon-e** [comment]
this PR still exits mid-PoW for me,
I send a kill message like so: 
```
sudo kill `docker inspect --format {{.State.Pid}} 4c1492fab301`
```
```
➜  private_tangle (karimodm-graceful-shutdown|…) % ./03_run_coordinator.sh -broadcast          
2019-04-17 12:27:36:986 +0000 [main] INFO org.iota.compass.Coordinator - loaded index 1
2019-04-17 12:27:37:213 +0000 [main] INFO org.iota.compass.Coordinator - Setup
2019-04-17 12:27:37:262 +0000 [main] INFO org.iota.compass.Coordinator - Starting index from: 1
2019-04-17 12:27:37:262 +0000 [main] INFO org.iota.compass.Coordinator - Setting milestone tick rate (ms) to: 10000
2019-04-17 12:27:37:262 +0000 [main] INFO org.iota.compass.Coordinator - Setting initial depth to: 3
2019-04-17 12:27:37:262 +0000 [main] INFO org.iota.compass.Coordinator - Validating Coordinator addresses.
2019-04-17 12:27:37:285 +0000 [main] INFO org.iota.compass.Coordinator - Issuing milestone: 2
2019-04-17 12:27:37:285 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: MKXEFFFM9YODEFWIBBVQXGQIDSCYEYHHKTXEBVHXEYIKFEK9GNLTFVTIRUOLQDXOTUNJNRLZ9XHS99999 Branch: MKXEFFFM9YODEFWIBBVQXGQIDSCYEYHHKTXEBVHXEYIKFEK9GNLTFVTIRUOLQDXOTUNJNRLZ9XHS99999
2019-04-17 12:28:18:036 +0000 [Shutdown Hook] INFO org.iota.compass.Coordinator - Shutting down Compass after next milestone...
➜  private_tangle (karimodm-graceful-shutdown|…) % 
```

**Comment by karimodm** [comment]
This is really strange... `pow.performPoW` is only called from within the `db.MilestoneDatabase` class, which is only invoked from the `createAndBroadcastMilestone` method. Can you run your compass under a debugger and grab a stack trace dump of all the threads at the the time of the `return` inside the `if (shutdown)` ?. As far as I can tell there should not be other threads that might hit that return and create a process exit code.

**Comment by karimodm** [comment]
Just wondering now if sending a signal from outside the context of the container might affect the behaviour of the containerized process. Can you please send a `SIGTERM` and `SIGINT` from within the container (`docker exec -it` to obtain a shell into it)?

**Comment by karimodm** [comment]
Disregard the comments above: it was my misunderstanding on how the JVM threats shutdown hooks; let me have another look at this.

**Comment by karimodm** [comment]
The JVM will halt when shutdown and finalization hook threads terminate; which means that the shutdown hook explicitly needs to wait for the worker thread to complete before exiting itself. Patched the PR.

File: compass/Coordinator.java [hunk 1]
```diff
@@ -262,6 +280,11 @@ private void start() throws InterruptedException {
         }
         //normal flow
         else {
+          // We want to perform shutdown only when we are ready to issue the next normal milestone
+            // and the node is in sync with the latest milestone we issued.
+          if (shutdown) {
```
Comment (alon-e) [inline compass/Coordinator.java]: small caveat - this will not stop the bootstrap stage, so if I run w/ `-bootstrap` it will only stop on the 3rd milestone:

```
2019-04-18 11:02:34:763 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 1
2019-04-18 11:02:34:763 +0000 [main] INFO org.iota.compass.Coordinator - Depth: 3 -> 3
2019-04-18 11:02:34:769 +0000 [main] INFO org.iota.compass.Coordinator - stored index 1
2019-04-18 11:02:44:775 +0000 [main] INFO org.iota.compass.Coordinator - Reusing last milestone.
2019-04-18 11:02:44:776 +0000 [main] INFO org.iota.compass.Coordinator - Issuing milestone: 2
2019-04-18 11:02:44:776 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: MXBXNLPXCDNJZQNHBLRBSSSKWMJBCBYHHSHETQXWQFBIXNBEYIXECUEHSUXHNMXFMPUTKPJGYZ9TW9999 Branch: 999999999999999999999999999999999999999999999999999999999999999999999999999999999
2019-04-18 11:02:47:007 +0000 [Shutdown Hook] INFO org.iota.compass.Coordinator - Shutting down Compass after next milestone...
2019-04-18 11:03:00:813 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 2
2019-04-18 11:03:00:813 +0000 [main] INFO org.iota.compass.Coordinator - Depth: 3 -> 3
2019-04-18 11:03:00:814 +0000 [main] INFO org.iota.compass.Coordinator - stored index 2
2019-04-18 11:03:10:821 +0000 [main] INFO org.iota.compass.Coordinator - Reusing last milestone.
2019-04-18 11:03:10:821 +0000 [main] INFO org.iota.compass.Coordinator - Issuing milestone: 3
2019-04-18 11:03:10:821 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: AONPB9NU9ICYRVMPMBGCDKIYVXVGQETAXZY9AFLMJFDBDBQLKKAREBRJISCGEPBONRKGYHXOXNMN99999 Branch: 999999999999999999999999999999999999999999999999999999999999999999999999999999999
2019-04-18 11:03:15:305 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 3
2019-04-18 11:03:15:305 +0000 [main] INFO org.iota.compass.Coordinator - Timestamp delta: 14491
2019-04-18 11:03:15:305 +0000 [main] INFO org.iota.compass.Coordinator - Depth: 3 -> 3
2019-04-18 11:03:15:306 +0000 [main] INFO org.iota.compass.Coordinator - stored index 3
➜  private_tangle (karimodm-graceful-shutdown|…) % 
```

Comment (karimodm) [reply compass/Coordinator.java]: This was made on purpose! I just want it to handle a graceful shutdown when reached a "normal" operation mode. Interrupting bootstrap mid-flight should be explicitly forced.
Do you agree?

Comment (alon-e) [reply compass/Coordinator.java]: yes, I agree. just wanted to make sure it was done knowingly.
